name: Production Deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "----------- START DEPLOY -----------"
            echo "User: $(whoami)"
            
            # Go to folder
            cd /home/lunix/Miet_Vuon_Restaurant
            
            # Update code
            git pull origin main
            
            # Restart Docker
            sudo docker-compose up -d --build
            sudo docker image prune -a -f
            echo "----------- DEPLOY SUCCESS -----------"

